name: Unzip ZIP file

on:
  push:
    paths:
      - "*.zip"   # jalanin workflow cuma kalau ada file zip di-push

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip file
        run: |
          for f in *.zip; do
            unzip "$f" -d extracted/
            rm "$f"
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-unzip uploaded zip"
          git push
